import type { CaseStudy } from "../types";

export const enterpriseLogisticsSaas: CaseStudy = {
  slug: "enterprise-logistics-saas",
  mission: "01",
  title: "Enterprise Logistics SaaS",
  titleLines: ["Enterprise", "Logistics SaaS"],
  summary:
    "Supported delivery of an enterprise SaaS platform for the international transport of large and small aerospace components, across the full lifecycle from stakeholder kickoff to go live.",
  categories: ["Enterprise SaaS", "Digital Transformation"],
  year: "Delivered",
  status: "completed",
  statusLabel: "Completed · Delivered",
  contribution: "Business analysis and prototyping across the full SaaS delivery lifecycle",
  role: "Business Analyst",
  preview: "grid",
  accent: "cyan",
  featured: true,
  snapshot: {
    role: "Business Analyst",
    projectType: "Enterprise SaaS · cross-organisation digital transformation",
    timeline: "Full delivery lifecycle, kickoff to go live",
    tools: ["Axure RP 9", "PRD and specification documentation", "Field dictionary", "Functional test cases", "Defect tracking"],
    team: "Delivered as part of a cross-organisation project team spanning client stakeholders, delivery partners and engineering",
    status: "Delivered and handed over",
  },
  seoDescription:
    "Business analysis, Axure RP 9 prototyping, requirement definition, testing and documentation supporting delivery of an enterprise logistics SaaS platform for aerospace component transportation.",
  blocks: [
    {
      kind: "note",
      id: "confidentiality",
      label: "Confidentiality",
      tone: "cyan",
      body: "Client and partner organisations are described by sector rather than by name throughout this case study. Everything below concerns the work and the process, not the parties.",
    },
    {
      kind: "prose",
      id: "context",
      label: "Context",
      body: [
        "A global aerospace manufacturer and an international logistics partner needed a governed SaaS platform to run the movement of aerospace components — items ranging from small parts to assemblies that require specialist international transport.",
        "The operation being replaced ran largely on manual process, accumulated convention and the knowledge of the people who had always done it. Multiple organisations were involved, each with its own systems, vocabulary and idea of where the process began and ended.",
      ],
    },
    {
      kind: "pillars",
      id: "problem",
      label: "Problem",
      items: [
        {
          k: "The process was never written down",
          tone: "orange",
          body: "There was no single authoritative description of how components actually moved. What existed lived in fragments across teams, and every fragment was correct from where its owner sat.",
        },
        {
          k: "Every team had exceptions",
          tone: "cyan",
          body: "Each stakeholder group described its own edge cases as the rule. Reconciling those competing accounts was the real analytical work, not documenting any one of them.",
        },
        {
          k: "Cross-organisation alignment",
          tone: "cyan",
          body: "Decisions needed agreement across organisational boundaries, where nobody had unilateral authority and terminology differed between parties.",
        },
        {
          k: "Specification drift",
          tone: "orange",
          body: "Without a maintained source of truth, the gap between what was agreed in a workshop and what reached development would widen with every sprint.",
        },
      ],
    },
    {
      kind: "list",
      id: "objectives",
      label: "Objectives",
      items: [
        "Surface and document the true end-to-end logistics process across organisations",
        "Reconcile contradictory accounts into one specification all parties could accept",
        "Give stakeholders something concrete to react to before development committed effort",
        "Define every data field once, unambiguously, with an owner",
        "Keep the build aligned to the agreed specification through delivery",
        "Leave the client's team able to operate the platform without the delivery team",
      ],
    },
    {
      kind: "list",
      id: "users",
      label: "Users & stakeholders",
      dense: true,
      items: [
        "Logistics and transport operations teams using the platform daily",
        "Manufacturing and supply-chain planners upstream of the movement",
        "Business process owners across multiple organisations",
        "The engineering team building against the specification",
        "Quality and testing stakeholders validating the delivered system",
        "Project sponsors accountable for the transformation programme",
      ],
    },
    {
      kind: "prose",
      id: "role",
      label: "My role",
      body: [
        "I contributed as a Business Analyst within a cross-organisation delivery team. The work was to turn an undocumented, contested process into a specification an engineering team could build from — and then to stay with it through development, testing and handover so the built system still matched what had been agreed.",
        "I did not lead the programme. The value I added was in the connective work: facilitating the sessions where the real process surfaced, making it tangible as prototypes, writing it down precisely, and holding that record steady as the build progressed.",
      ],
    },
    {
      kind: "list",
      id: "responsibilities",
      label: "Responsibilities",
      dense: true,
      intro:
        "Verbs chosen precisely. This was team delivery, and these are the parts I was accountable for.",
      items: [
        "Opened and presented the project at a large stakeholder meeting",
        "Introduced the project scope and delivery direction",
        "Designed interactive prototypes using Axure RP 9",
        "Organised recurring weekly project meetings",
        "Reported development progress",
        "Raised and clarified business-process questions",
        "Collected and refined business requirements",
        "Contributed to the PRD",
        "Created a field dictionary",
        "Supported development communication",
        "Conducted functional testing",
        "Identified and helped debug system issues",
        "Documented defects and validation results",
        "Prepared the user manual",
        "Supported final delivery and knowledge transfer",
        "Contributed to successful project completion",
      ],
    },
    {
      kind: "prose",
      id: "discovery",
      label: "Discovery & analysis",
      body: [
        "Discovery started with the assumption that everyone was telling the truth and no two accounts would match. Facilitated sessions were run to get the competing versions into the same room, where the contradictions became visible and could be resolved by the people who owned them rather than by the analyst guessing.",
        "The prototype was the analytical instrument, not the deliverable. Written requirements get nodded at; a clickable screen gets argued with. Putting an interactive Axure prototype in front of stakeholders reliably surfaced constraints that had gone unmentioned for weeks — because it is much easier to say \"that field is wrong\" than to describe a field from memory.",
        "The field dictionary came out of the same instinct. Once each data element had one definition, one type, one source and one owner, a whole class of downstream disagreement simply stopped occurring.",
      ],
    },
    {
      kind: "prose",
      id: "solution",
      label: "Solution",
      body: [
        "A governed SaaS platform replacing manual coordination for international component movement, specified through an interactive prototype, a PRD and a field dictionary that together formed the single source of truth for the build.",
        "The specification was deliberately treated as a maintained artefact rather than a document produced once. As the build raised questions, answers went back into the specification, so what shipped and what was agreed stayed the same thing.",
      ],
    },
    {
      kind: "flow",
      id: "timeline",
      label: "Delivery timeline",
      variant: "timeline",
      intro: "Ten stages from introduction to delivery. I was involved across all of them.",
      steps: [
        { name: "Project introduction", desc: "Opened and presented the project at a large stakeholder meeting, setting out scope and delivery direction." },
        { name: "Stakeholder alignment", desc: "Recurring weekly sessions established a shared vocabulary and a forum where cross-organisation decisions could actually be made." },
        { name: "Business-process discovery", desc: "Facilitated sessions surfaced the undocumented process and put competing accounts side by side so contradictions could be resolved." },
        { name: "Axure prototype", desc: "Interactive prototypes stakeholders could click, break and argue with — the fastest route to unspoken constraints." },
        { name: "Requirement validation", desc: "Requirements collected, refined and confirmed against the prototype, with edge cases named and scope boundaries made explicit." },
        { name: "PRD & field dictionary", desc: "Contributed to the product requirements document and created the field dictionary: every data element defined once, with type, source and ownership." },
        { name: "Development coordination", desc: "Supported development communication, reported progress and clarified business-process questions as they arose during the build." },
        { name: "Testing & debugging", desc: "Conducted functional testing, identified issues, helped debug them, and documented defects and validation results." },
        { name: "User documentation", desc: "Prepared the user manual, written for the operator on a busy day rather than for a reviewer." },
        { name: "Delivery", desc: "Supported final delivery and knowledge transfer, leaving the client team able to run the platform independently." },
      ],
    },
    {
      kind: "features",
      id: "artefacts",
      label: "Artefacts produced",
      items: [
        { name: "Interactive Axure RP 9 prototype", desc: "Clickable flows used to validate requirements before development committed effort." },
        { name: "Product requirements documentation", desc: "Contributed flows, states, rules and acceptance criteria to the specification the build worked from." },
        { name: "Field dictionary", desc: "Every data element defined once — type, source, ownership and validation — removing a recurring source of ambiguity." },
        { name: "Functional test coverage", desc: "Scenarios written from the business process rather than from the screens, so gaps in logic surfaced rather than gaps in UI." },
        { name: "Defect records", desc: "Issues documented with reproducible business context attached, and tracked through to closure." },
        { name: "User manual", desc: "Operational documentation supporting handover and independent use." },
      ],
    },
    {
      kind: "prose",
      id: "testing",
      label: "Testing & iteration",
      body: [
        "Functional testing was written from the process rather than the interface. Testing what the screens do finds interface bugs; testing what the business does finds the cases where the built logic and the agreed logic have quietly diverged.",
        "Defects were documented with the business context needed to reproduce them, which shortened the loop considerably — an engineer given the scenario and the reason usually needs no follow-up conversation.",
      ],
    },
    {
      kind: "pillars",
      id: "outcome",
      label: "Delivery outcome",
      items: [
        {
          k: "Delivered to production",
          tone: "orange",
          body: "The platform reached delivery with the documented process, tested build and operational documentation in place.",
        },
        {
          k: "A maintained source of truth",
          tone: "cyan",
          body: "PRD and field dictionary remained current through the build, so the delivered system and the agreed specification stayed aligned.",
        },
        {
          k: "Knowledge transferred",
          tone: "cyan",
          body: "Handover and user documentation left the client's team able to operate the platform without the delivery team present.",
        },
        {
          k: "Full-lifecycle involvement",
          tone: "orange",
          body: "Contribution spanned introduction, discovery, prototyping, specification, development support, testing, documentation and delivery.",
        },
      ],
    },
    {
      kind: "prose",
      id: "lessons",
      label: "Lessons learned",
      body: [
        "The deliverable everyone asks for is the specification; the deliverable that actually moves a project is the prototype, because it converts vague agreement into specific disagreement early enough to be cheap.",
        "In cross-organisation work, most apparent requirement conflicts are vocabulary conflicts. A large share of the analysis was establishing that two teams using different words meant the same thing — and, less often but more importantly, that two teams using the same word did not.",
        "Staying with a specification through testing and handover changes what you write. Knowing you will be the one testing it, and the one writing the manual, produces noticeably more precise requirements than writing a document you will never meet again.",
      ],
    },
  ],
};
